### ISSUE TITLE
URL to open a local file? or export a preview?

### ISSUE THREAD

**Issue by jkitchin** [alswl/excalidraw-collaboration#11]
This is amazing!

Is there a way to construct a url or http request to open a file at a known path? e.g. 127.0.0.1/Untitled-2023-02-18-0800.excalidraw that opens this file in the browser?

I am able to open from the excalidraw window, but since I know where it is, I would like to be able to just open the file.

It would also be very helpful to be able to generate a request/url that generates an svg preview.

**Comment by alswl** [comment]
> I am able to open from the excalidraw window

This sounds strange, because a site should not have permission to open local files. Can you tell me how to open the file in the excalidraw window? Drag the file to https://excalidraw.com/ ?

This project is just building an excalidraw instance with three parts: front-end, back-end and collaboration server. I can't provide more features than the official excalidraw.

**Comment by jkitchin** [comment]
you just click on the hamburger menu in the upper left and select open (or cmd-O) and browse to the file. You can also just drag a local file onto the browser window at 127.0.0.1.

It seems now you can install excalidraw locally as a Chrome app (https://twitter.com/excalidraw/status/1249710826535206913?lang=en). With this you can make a "hyperlink" that chrome knows how to open.

There are also some cmd line utilities for the export I found since yesterday (https://github.com/Timmmm/excalidraw_export).

I hoped these were features already in excalidraw I just didn't know about.

**Comment by alswl** [comment]
@jkitchin 

The excalidraw(exclude the collaboration features) is pure font-end project. So if you want generate an svg file for preview, you should put this file into the exist frontend project.

For example:

- https://www.npmjs.com/package/@excalidraw/excalidraw works for react framework
- https://github.com/zsviczian/obsidian-excalidraw-plugin works for Obsidian

As I said,  this project is a simple building system to construct the collaboration excalidraw. I think you should found others projects.
