### ISSUE TITLE
room function not working

### ISSUE THREAD

**Issue by sephymartin** [alswl/excalidraw-collaboration#12]
I followed the " Build and Run step ", bet I can't use the room function. 

### The browser console show this
**console**
<img width="776" alt="image" src="https://user-images.githubusercontent.com/299891/225620715-fc575fca-6fb9-457d-bbc5-aa5f522e68e9.png">
**javascript source**
<img width="683" alt="image" src="https://user-images.githubusercontent.com/299891/225620939-b6a5e0b4-39d4-4494-95fa-9aec72ce35bd.png">

```
encryption.ts:16 
        
       Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'generateKey')
    at encryption.ts:16:42
    at f (regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (regeneratorRuntime.js:125:22)
    at Generator.next (regeneratorRuntime.js:69:21)
    at r (asyncToGenerator.js:3:20)
    at l (asyncToGenerator.js:22:9)
    at asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at asyncToGenerator.js:19:12
    at encryption.ts:11:35
```

my excalidraw.env.production

```
REACT_APP_BACKEND_V2_GET_URL=https://test.com/api/v2/
REACT_APP_BACKEND_V2_POST_URL=https://test.com/api/v2/post/

REACT_APP_LIBRARY_URL=https://libraries.excalidraw.com
REACT_APP_LIBRARY_BACKEND=https://us-central1-excalidraw-room-persistence.cloudfunctions.net/libraries

REACT_APP_HTTP_STORAGE_BACKEND_URL=http://192.168.100.77:5081/api/v2
REACT_APP_STORAGE_BACKEND=http

REACT_APP_PORTAL_URL=
# Fill to set socket server URL used for collaboration.
# Meant for forks only: excalidraw.com uses custom REACT_APP_PORTAL_URL flow
REACT_APP_WS_SERVER_URL=http://192.168.100.77:5082

REACT_APP_FIREBASE_CONFIG='{}'

# production-only vars
REACT_APP_GOOGLE_ANALYTICS_ID=foo

REACT_APP_PLUS_APP=https://app.excalidraw.com
```

Whether exists any docker image with room function I can use it directly?

**Comment by alswl** [comment]
The crypto modules in JavaScript requires HTTPS connections, so you require
setup the SSL cert on your access layer(like Nginx).

Martin ***@***.***>于2023年3月16日 周四20:47写道：

**Comment by alswl** [comment]
duplicated with https://github.com/alswl/excalidraw-collaboration/issues/4
