### ISSUE TITLE
Sharing and storing in DB doesn't work.

### ISSUE THREAD

**Issue by freezah** [alswl/excalidraw-collaboration#14]
Hi, 

does not work when using haproxy and trusted SSL certificates (all three components configured with HTTPS).

Do you have any working example of docker-compose.yaml and .env for public internet domains ?

**Comment by alswl** [comment]
Please show me the error message.

**Comment by alswl** [comment]
@freezah I'm so sad, the error message is not provided by Docker or NodeJS(entrypoint). The error is beyond this project, I'can't provide helps.

**Comment by freezah** [comment]
@alswl , ok, understood. Although my question is have you successfully deployed excalidraw + room + storage on a remote server publicly available over https ?

**Comment by alswl** [comment]
@freezah I'm sure it works. You can check https://draw2.dmitrysamoylenko.in/#room=f8671f3fdef3ada5128c,Dyn8aqg8RII9rzUVIl9i7w .

You should check the request chains of your deployments.

And the excalidraw-room project is depend on crypto module, it required HTTPS protocol.

**Comment by alswl** [comment]
@freezah I see. I think the sample(provide by another developer) was not works as expected properly.
But in my self-host domain(a private intranet deploy), it works.

I'm lack of cloud resources , so I cannot provide a online demo.

**Comment by an-hen** [comment]
I experience the same issue.

@freezah could you find a solution for the problem?

The error log message indicates, that a Firebase project id is missing.

@alswl Would it be possible for you to show us your `excalidraw.env.production` file?

**Comment by alswl** [comment]
Thanks to @an-hen .

Yes, `REACT_APP_STORAGE_BACKEND` shows the storage provider is firebase or http server, not the schema.
