### ISSUE TITLE
unknown flag: --progress

### ISSUE THREAD

**Issue by MuratovAS** [alswl/excalidraw-collaboration#15]
https://github.com/alswl/excalidraw-collaboration/blob/c303948cbbc9c1acb352d25af01c499f0c829a74/Makefile#L71

```
DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            Install the buildx component to build images with BuildKit:
            https://docs.docker.com/go/buildx/

unknown flag: --progress
See 'docker build --help'.
```

I solved this problem by deleting the line

**Comment by alswl** [comment]
Please show me your docker version by command line `docker --version`.

**Comment by MuratovAS** [comment]
> Please show me your docker version by command line `docker --version`.

Docker version 23.0.6, build ef23cbc431

**Comment by jordanriley1992** [comment]
Docker version 23.0.6, build ef23cbc

**Comment by alswl** [comment]
My local docker version is `Docker version 23.0.5, build bc4487a`.

I switch to 23.0.5, I found the information(`docker build --help`):

```
DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            Install the buildx component to build images with BuildKit:
            https://docs.docker.com/go/buildx/
```

It seems documented in https://docs.docker.com/engine/deprecated/#legacy-builder-fallback , but the `--progress` argument is lack of description.

Maybe you can downgrade your docker version, or install https://github.com/docker/buildx#linux-packages and using `docker buildx build`
