### ISSUE TITLE
updates

### ISSUE THREAD

**Issue by Unkn0wnCreator** [alswl/excalidraw-collaboration#23]
hi, 

Will this get upstream upgrades? Like upgrades from upstream excalidraw

**Comment by alswl** [comment]
Sure, the version is matched to upstream, and I will bump version after
upstream upgrade.

Unkn0wnCreator ***@***.***>于2023年8月9日 周三06:31写道：

**Comment by alswl** [comment]
@Unkn0wnCreator I'm still on my vacation, updates will be coming soon.
