### ISSUE TITLE
excalidraw可以升级到官方的新版本吗

### ISSUE THREAD

**Issue by yinhuihe** [alswl/excalidraw-collaboration#24]
首先感谢大佬 @alswl 
我用你的代码已经成功部署了excalidraw-collaboration，并且完美支持协作功能，由于不懂开发，希望大佬可以更新一下excalidraw或者提供一下升级思路，非常感谢！！

**Comment by alswl** [comment]
@yinhuihe 
Master 代码就是最新的 v0.15.0，tag 我还没有 Release，等我自己环境部署验证再打 tag 出来。
