### ISSUE TITLE
Support for v0.16.0?

### ISSUE THREAD

**Issue by rizlas** [alswl/excalidraw-collaboration#32]
This fork will be updated to complain with v0.16.0 breaking changes?

**Comment by rizlas** [comment]
Hi,
if you sync your fork I'll contribute. I already have a setup based on 0.16.1 with your modifications.

**Comment by alswl** [comment]
I'm focusing to build the container image, it required using the react app env dynamic in the container start.
It will take a little more time to solve the problems.

I will upgrade to 0.16.0 after the build system upgraded.

**Comment by klepptor** [comment]
This would be awesome! ;)

**Comment by rizlas** [comment]
This is my approach https://github.com/rizlas/excalifork/tree/master and support to 0.16.1

**Comment by alswl** [comment]
@rizlas @klepptor 
Upgraded.
