### ISSUE TITLE
v0.16.1-fork-b1版本部署后实时协作存在异常

### ISSUE THREAD

**Issue by xcz1997** [alswl/excalidraw-collaboration#35]
![image](https://github.com/alswl/excalidraw-collaboration/assets/20314747/1dc5c844-816d-4712-8ccd-1d3ba066f1b9)
<img width="1258" alt="image" src="https://github.com/alswl/excalidraw-collaboration/assets/20314747/15c16f0e-87ee-432f-8a7b-c61f679c7cfa">
本以为是自己部署的问题，发现live 的也是一样的问题，回滚到上个版本后清空缓存正常

**Comment by alswl** [comment]
@xcz1997 你在这个环境工作正常么？
https://excalidraw-collaboration.zeabur.app/

注意，最新的配置需要将 REACT_APP 换成 VITE_APP。

**Comment by xcz1997** [comment]
> @xcz1997 你在这个环境工作正常么？ https://excalidraw-collaboration.zeabur.app/
> 
> 注意，最新的配置需要将 REACT_APP 换成 VITE_APP。

确实是我的问题，没有注意到环境变量的改动，将 REACT_APP 换成 VITE_APP后，0.16.1 正常工作，感谢！
