### ISSUE TITLE
Problem with connecting with storage backend

### ISSUE THREAD

**Issue by Farapholch** [alswl/excalidraw-collaboration#42]
Hi!
I'm recieving this error message when trying the collaboration feature and connecting to storage:

"Couldn't save to the backend database. If problems persist, you should save your file locally to ensure you don't lose your work."

![image](https://github.com/alswl/excalidraw-collaboration/assets/52049523/2c759f6d-9c65-4682-a0ed-dc36fca7bed0)

When Accessing Storage Backend Url I get 404:
https://excalistorage-devspace.domain/api/v2    

![image](https://github.com/alswl/excalidraw-collaboration/assets/52049523/1ddaa065-0f1a-491b-8b2a-0fab22987f8b)

The Storage backend config is as follows:

```
- name: VITE_APP_HTTP_STORAGE_BACKEND_URL
  value: https://excalistorage-devspace.domain/api/v2     
- name: VITE_APP_STORAGE_BACKEND              
 value: https://excalistorage-devspace.domain/api/v2
```

**Comment by alswl** [comment]
Check your load balancer configuration, and make sure `https://excalistorage-devspace.domain/api/v2` access the right backend service.
