### ISSUE TITLE
无法保存到后端数据库。如果问题持续存在，您应该保存文件到本地，以确保您的工作不会丢失。

### ISSUE THREAD

**Issue by xvbai0317** [alswl/excalidraw-collaboration#48]
这是我的docker-compose.yaml
version: "3.8"

services:
  frontend:
    image: alswl/excalidraw:v0.17.0-fork-b2
    environment:
      - VITE_APP_BACKEND_V2_GET_URL=https://test.com/api/v2/
      - VITE_APP_BACKEND_V2_POST_URL=https://test.com/api/v2/post/
      - VITE_APP_WS_SERVER_URL=http://huatu.iris-sci.cn:8082
      - VITE_APP_FIREBASE_CONFIG={}
      - VITE_APP_HTTP_STORAGE_BACKEND_URL=http://huatu.iris-sci.cn:8081/api/v2
      - VITE_APP_STORAGE_BACKEND=http
    ports:
     - 8085:80

  storage:
    image: alswl/excalidraw-storage-backend:v2023.11.11
    restart: always
    environment:
      - PORT=8081
      - STORAGE_URI=redis://redis:6379
    ports:
      - 8081:8081

  room:
    image: excalidraw/excalidraw-room:sha-49bf529
    ports:
      - 8082:80

  redis:
    image: redis
    ports:
     - "6378:6379"
    volumes:
      - ./redis_data/data:/data

![d86eb495353192aa2807d54bdbcbf76e](https://github.com/alswl/excalidraw-collaboration/assets/92377243/d2970063-cf80-454f-892e-dc92d7814a7e)

**Comment by alswl** [comment]
所有域名都需要是 HTTPS。浏览器禁止在 HTTPS 页面发起 HTTP 请求。

**Comment by xvbai0317** [comment]
我修改了我的docker-compose但是好像没有效果
version: "3.8"

services:
  frontend:
    image: alswl/excalidraw:v0.17.0-fork-b2
    environment:
      - VITE_APP_BACKEND_V2_GET_URL=https://test.com/api/v2/
      - VITE_APP_BACKEND_V2_POST_URL=https://test.com/api/v2/post/
      - VITE_APP_WS_SERVER_URL=https://huatu.iris-sci.cn:8082
      - VITE_APP_FIREBASE_CONFIG={}
      - VITE_APP_HTTP_STORAGE_BACKEND_URL=https://huatu.iris-sci.cn:8081/api/v2
      - VITE_APP_STORAGE_BACKEND=https
    ports:
     - 8085:80

  storage:
    image: alswl/excalidraw-storage-backend:v2023.11.11
    restart: always
    environment:
      - PORT=8081
      - STORAGE_URI=redis://redis:6379
    ports:
      - 8081:8081

  room:
    image: excalidraw/excalidraw-room:sha-49bf529
    ports:
      - 8082:80

  redis:
    image: redis
    ports:
     - "6378:6379"
    volumes:
      - ./redis_data/data:/data
![060a8eca69e5632ad86848f5cff59f76](https://github.com/alswl/excalidraw-collaboration/assets/92377243/577c2c6c-68a2-4cb2-85d8-a727a10914cb)
会和下面这个图中我的8082端口的情况有关吗
![06fe92533112c1b48b18bc8b164296c9](https://github.com/alswl/excalidraw-collaboration/assets/92377243/2c44b31c-8190-4518-a327-c268e2479287)

**Comment by xvbai0317** [comment]
会和下面这个图中我的8082端口的情况有关吗
![06fe92533112c1b48b18bc8b164296c9](https://github.com/alswl/excalidraw-collaboration/assets/92377243/2c44b31c-8190-4518-a327-c268e2479287)

**Comment by xvbai0317** [comment]
server{
        #HTTPS的默认访问端口443。
     	#如果未在此处配置HTTPS的默认访问端口，可能会造成Nginx无法启动。
     	listen 443 ssl;
     
     	#填写证书绑定的域名
     	server_name huatu.iris-sci.cn;
 
     	#填写证书文件绝对路径
     	ssl_certificate cert/huatu.iris-sci.cn.pem;
     	#填写证书私钥文件绝对路径
     	ssl_certificate_key cert/huatu.iris-sci.cn.key;
 
     	ssl_session_cache shared:SSL:1m;
     	ssl_session_timeout 5m;
	 
     	#自定义设置使用的TLS协议的类型以及加密套件（以下为配置示例，请您自行评估是否需要配置）
     	#TLS协议版本越高，HTTPS通信的安全性越高，但是相较于低版本TLS协议，高版本TLS协议对浏览器的兼容性较差。
     	ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE:ECDH:AES:HIGH:!NULL:!aNULL:!MD5:!ADH:!RC4;
     	ssl_protocols TLSv1.1 TLSv1.2 TLSv1.3;

     	#表示优先使用服务端加密套件。默认开启
     	ssl_prefer_server_ciphers on;
 
 
    #	location / {
    #       proxy_pass http://172.22.166.16:8085;
    #       #index index.html index.htm;
    #       proxy_http_version 1.1;  
    #       proxy_set_header Upgrade $http_upgrade;  
    #       proxy_set_header Connection "upgrade";
   # 	}
              
         location / {
            proxy_set_header Host $host;
            proxy_pass http://172.22.166.16:8085;
        }

        location /api/v2 {
            proxy_set_header Host $host;
            proxy_pass http://172.22.166.16:8081;
        }

        location /socket.io/ {
            proxy_pass http://172.22.166.16:8082;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
        }




    access_log  /www/wwwlogs/access.log;
    error_log /www/wwwlogs/huatu.iris-sci.cn_error.log notice;
 }
这个是nginx

**Comment by xvbai0317** [comment]
![2151706261437_ pic](https://github.com/alswl/excalidraw-collaboration/assets/92377243/ca28c5a2-dc78-44a6-bc6b-ff09ab518856)
而且我改完docker-compose之后，这里发的仍然是http请求
