### ISSUE TITLE
Images not working when "Export to Link" was used

### ISSUE THREAD

**Issue by Someone0nEarth** [alswl/excalidraw-collaboration#53]
First things first: Thanks for your work!!

I got the collaboration mode to work, but there are some anomalies when dealing with images:

Images working fine in the collaboration mode:

![grafik](https://github.com/alswl/excalidraw-collaboration/assets/99350163/1d80295c-8c2c-47dc-bf56-35392c2eb95d)

Until someone did a save using "Export to Link". When using the link, only a placeholder for the image will be shown:

![grafik](https://github.com/alswl/excalidraw-collaboration/assets/99350163/361686fd-4ecb-40c5-a2a6-5969d2060641)

When using the room-share link after doing the "Export to Link" the images wont be shown too.

When doing a "Save to disk", the images are referenced in "elements", but the "files" are empty.

#### 1) Export to Link

1. Create a new drawing and pasting an image into it.
2. Do a "Export to Link"
3. Using the export-link: Now, only the placeholder will be shown 

#### 2) Export to Link after starting a Live Collaboration

1. Create a new drawing and pasting an image into it.
2. Starting a  "Live collaboration": Image will be shown, when using the collaboration-link
3. Do a "Export to Link"
4. Using the collaboration-link: Now, only the placeholder will be shown (the same when using the export-link)

#### 3) Export to Link before starting a Live Collaboration

1. Create a new drawing and pasting an image into it.
2. Do a "Export to Link" 
3. Using the export-link: Now, only the placeholder will be shown 
4. NOW start a "Live collaboration"
5. Using the collaboration-link: Now, the image (!) will be shown 
6. Do another "Export to Link" 
7. Using the collaboration-link again:  Now, only the placeholder (!) will be shown

### Summary

As soon as a "Export to link" was done, images will be shown only as a placeholder. Beside the one special case in 3), when a collaboration session was`t started, it will work until the next "Export to link" for the collaboration mode.

Btw: When restarting all the services, images will still be shown when using the collaboration link (until the drawing was "exported to link"). So there is some kind of working image persistence.

I'm using `alswl/excalidraw:v0.17.0-fork-b2`, `alswl/excalidraw-storage-backend:v2023.11.11` and `excalidraw/excalidraw-room:sha-49bf529`. But same behavior when using `excalidraw/excalidraw-room`.

I tried this with redis, postgres and mongodb.

**Comment by Someone0nEarth** [comment]
Some more additional infos:

Rooms, scenes and files are stored in the mongo:

![grafik](https://github.com/alswl/excalidraw-collaboration/assets/99350163/b97ab0ef-00d2-4d4a-ad79-c36677baf01e)

And using "rooms" only, files working as aspected, until a scene with this file is created.. than files won`t load for rooms and scenes. In the file-exports, the linked "fileId" is correct and still present in the db. Even the file itself is identical, besides "files" is empty: `"files": {}`

**Comment by Someone0nEarth** [comment]
Hello again,

I did a little more digging into it. My knowledge of Javascript frameworks etc are limited... but maybe these are the reasons, why files are not working with "http storage" as soon they are is in scenes:

https://github.com/alswl/excalidraw/blob/1d751e7dc15d1f1b00101e52cf1607bbedccef1c/excalidraw-app/index.tsx#L333

![grafik](https://github.com/alswl/excalidraw-collaboration/assets/99350163/6c964599-8550-4180-8bc4-0ed06db3a953)

https://github.com/alswl/excalidraw/blob/1d751e7dc15d1f1b00101e52cf1607bbedccef1c/excalidraw-app/index.tsx#L358

![grafik](https://github.com/alswl/excalidraw-collaboration/assets/99350163/0c1de704-1497-4da7-a311-5cc3b8ccb052)

As I said, my knowledge of JS etc. is limited, so, sadly, I won't be able to proof or fix this in a affordable time.

But maybe, this was helping ...

**Comment by Someone0nEarth** [comment]
> @Someone0nEarth I'm unable to even export the link, not sure whats wrong with my config, heres the error message:

Hey @farapholch I would bet, changing the backend GET and POST URL pathes too `/api/v2/scenes/` will [fix](https://github.com/alswl/excalidraw-collaboration/issues/28#issue-1910611271) your issues.

**Comment by farapholch** [comment]
@Someone0nEarth thank you so much! :) Now I can retrieve a link, but when I open the link I get a request for "https://json.excalidraw.com" instead of my url. Maybe something in the build.

![image](https://github.com/alswl/excalidraw-collaboration/assets/52049523/b31f801b-eeef-402c-aa9f-1a798c0a3af1)

**Comment by woremacx** [comment]
@alswl 
Thank you for the great changes.

I made some changes that I believe can solve this issue and have submitted a PR.
Please check it out.

[Init storageBackend before use it by woremacx · Pull Request #30 · alswl/excalidraw](https://github.com/alswl/excalidraw/pull/30)

**Comment by Someone0nEarth** [comment]
> @alswl Thank you for the great changes.
> 
> I made some changes that I believe can solve this issue and have submitted a PR. Please check it out.
> 
> [Init storageBackend before use it by woremacx · Pull Request #30 · alswl/excalidraw](https://github.com/alswl/excalidraw/pull/30)

Thanks @woremacx !! That fixed it! Now the images are working!!

@alswl Please pull woremacx fix :D

**Comment by alswl** [comment]
Now the new version is released, and the demo site( https://excalidraw-production-4d27.up.railway.app/) is upgraded.
You can check out the new image.

Thanks a lot to @Someone0nEarth and @woremacx .

**Comment by woremacx** [comment]
Thanks @alswl for great hack, and @Someone0nEarth for docker-compose files.
