### ISSUE TITLE
不能协作 不能导出link

### ISSUE THREAD

**Issue by pope-L** [alswl/excalidraw-collaboration#55]
如题请问怎么修改呢？

配置如下；

> 还有 - STORAGE_URI=redis://172.16.99.45:6379这里为何写成- STORAGE_URI=redis://localhost:6379会提示ECONNREFUSED 127.0.0.1:6379 [StorageService] Connection Error 

host bitest.ts.com 172.16.99.6 client
    nginx 
```
   server {
        listen       443 ssl;
        server_name  localhost;
        ssl_certificate      C:\Users\Administrator\Downloads\ui\web\chain.crt;
        ssl_certificate_key  C:\Users\Administrator\Downloads\ui\web\key.key;
        ssl_session_cache    shared:SSL:1m;
        ssl_session_timeout  5m;
        ssl_ciphers  HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers  on; 
        location / {
            proxy_pass http://172.16.99.45/;
        }  
    }
        server {
        listen       8081 ssl;
        server_name  localhost;
        ssl_certificate      C:\Users\Administrator\Downloads\ui\web\chain.crt;
        ssl_certificate_key  C:\Users\Administrator\Downloads\ui\web\key.key;
        ssl_session_cache    shared:SSL:1m;
        ssl_session_timeout  5m;
        ssl_ciphers  HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers  on; 
        location / {
            proxy_pass http://172.16.99.45:8081;
        }  
    }
        server {
        listen       8082 ssl;
        server_name  localhost;
        ssl_certificate      C:\Users\Administrator\Downloads\ui\web\chain.crt;
        ssl_certificate_key  C:\Users\Administrator\Downloads\ui\web\key.key;
        ssl_session_cache    shared:SSL:1m;
        ssl_session_timeout  5m;
        ssl_ciphers  HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers  on; 
        location / {
            proxy_pass http://172.16.99.45:8082;
        }  
    }
```
serv 172.16.99.45
   docker 

docker-compose.yaml

> # sample comes from https://github.com/docker/awesome-compose
> 
> services:
>   frontend:
>     image: alswl/excalidraw:v0.17.0-fork-b1
>     environment:
>       - PORT=8081
>       - VITE_APP_BACKEND_V2_GET_URL=https://bitest.ts.com/api/v2/
>       - VITE_APP_BACKEND_V2_POST_URL=https://bitest.ts.com/api/v2/post/
>       - VITE_APP_WS_SERVER_URL=https://bitest.ts.com:8082
>       - VITE_APP_FIREBASE_CONFIG={}
>       # alswl'fork env
>       # forked excalidraw can use env https://github.com/alswl/excalidraw/pull/5
>       - VITE_APP_HTTP_STORAGE_BACKEND_URL=https://bitest.ts.com:8081/api/v2
>       - VITE_APP_STORAGE_BACKEND=http
>     ports:
>       - 80:80
> 
>   storage:
>     image: alswl/excalidraw-storage-backend:v2023.11.11
>     restart: always
>     environment: # docs https://github.com/alswl/excalidraw-storage-backend#environement-variables
>       - STORAGE_URI=redis://172.16.99.45:6379
>       - PORT=8081
>     ports:
>       - 8081:8081
> 
>   room:
>     image: excalidraw/excalidraw-room:sha-49bf529
>     ports:
>       - 8082:80
>   rediss1:
>     image: redis
>     ports:
>       - 6379:6379
>

**Comment by Someone0nEarth** [comment]
Hi @pope-L this should fix your issue: https://github.com/alswl/excalidraw-collaboration/issues/53#issuecomment-1970151015

A working Docker Compose configuration can be found here: https://github.com/Someone0nEarth/excalidraw-self-hosted
