### ISSUE TITLE
Excalidraw image update

### ISSUE THREAD

**Issue by farapholch** [alswl/excalidraw-collaboration#57]
Hello!

Thanks for your great work! Do you have any plans for updating the Excalidraw version?

We saw that there are more support added for pen erasing: https://github.com/excalidraw/excalidraw/pull/7496

**Comment by alswl** [comment]
I'll release a version based on upstream v0.17.3 later. But your requirement is not include in the v0.17.3.

This repo will only follow the release of upstream, not the master branch.
The PR 7496 is merged, I think this will be released in the next version.

**Comment by farapholch** [comment]
Perfect! :)

**Comment by alswl** [comment]
https://github.com/alswl/excalidraw-collaboration/releases/tag/v0.17.3-fork-b1
Released.

**Comment by pope-L** [comment]
> https://github.com/alswl/excalidraw-collaboration/releases/tag/v0.17.3-fork-b1 Released.
chrome console 
FirebaseError: Firebase Storage: No default bucket found. Did you set the 'storageBucket' property when initializing the app? (storage/no-default-bucket)

image :v0.17.3-fork-b1

**Comment by alswl** [comment]
@pope-L Please open another issue to track. And it's better if you can provide snapshot.
The demo site (https://excalidraw-production-4d27.up.railway.app) is a good instance for reproduce problem.

**Comment by pope-L** [comment]
> @pope-L Please open another issue to track. And it's better if you can provide snapshot. The demo site (https://excalidraw-production-4d27.up.railway.app) is a good instance for reproduce problem.
哦 我知道了 是点导出excalidraw++ 那里 控制台的提示的信息 ，这个功能本来就没完成的是吧， 过一会大佬您应该看过了
这条信息，我1个钟后就删掉这个记录，费事呛眼
