### ISSUE TITLE
大佬可以帮忙上传到dockhub吗？

### ISSUE THREAD

**Issue by kingjoydom** [alswl/excalidraw-collaboration#7]

**Comment by matbgn** [comment]
Let me double this.

Would a sponsorship give you some motivation to put your images on docker hub or just here in the github registry https://ghcr.io via a github actions or some pipeline?

I would then be able to update the Caprover (https://caprover.com/) to the corresponding images https://github.com/caprover/one-click-apps/blob/master/public/v4/apps/excalidraw.yml

**Comment by alswl** [comment]
Done.

Please read the README.md .
