### ISSUE TITLE
make patch images时出错？如何解决？谢谢

### ISSUE THREAD

**Issue by jacknelson-sr** [alswl/excalidraw-collaboration#8]
#14 [builder  9/10] RUN npm ci --prod
#14 0.942 npm WARN config production Use `--omit=dev` instead.
#14 2.542 npm ERR! code EINVAL
#14 2.544 npm ERR! syscall rmdir
#14 2.545 npm ERR! path /app/node_modules/.bin
#14 2.548 npm ERR! errno -22
#14 2.550 npm ERR! EINVAL: invalid argument, rmdir '/app/node_modules/.bin'
#14 2.553 
#14 2.553 npm ERR! A complete log of this run can be found in:
#14 2.554 npm ERR!     /root/.npm/_logs/2023-02-08T12_37_38_527Z-debug-0.log
#14 ERROR: process "/bin/sh -c npm ci --prod" did not complete successfully: exit code: 234
------
 > [builder  9/10] RUN npm ci --prod:
#14 0.942 npm WARN config production Use `--omit=dev` instead.
#14 2.542 npm ERR! code EINVAL
#14 2.544 npm ERR! syscall rmdir
#14 2.545 npm ERR! path /app/node_modules/.bin
#14 2.548 npm ERR! errno -22
#14 2.550 npm ERR! EINVAL: invalid argument, rmdir '/app/node_modules/.bin'
#14 2.553 
#14 2.553 npm ERR! A complete log of this run can be found in:
#14 2.554 npm ERR!     /root/.npm/_logs/2023-02-08T12_37_38_527Z-debug-0.log
------
Dockerfile:13
--------------------
  11 |     
  12 |     COPY . .
  13 | >>> RUN npm ci --prod
  14 |     RUN npx nest build
  15 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c npm ci --prod" did not complete successfully: exit code: 234
make: *** [Makefile:65: images] Error 1

**Comment by jacknelson-sr** [comment]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'ci', '--pro' ]
2 info using npm@6.14.11
3 info using node@v10.24.0
4 verbose npm-session 83d0dd9ec0540751
5 info prepare initializing installer
6 verbose prepare starting workers
7 verbose prepare installation prefix: /root/excalidraw-collaboration
8 verbose teardown shutting down workers.
9 info teardown Done in 0.001s
10 verbose stack Error: ENOENT: no such file or directory, open '/root/excalidraw-collaboration/package.json'
11 verbose cwd /root/excalidraw-collaboration
12 verbose Linux 5.15.83-1-pve
13 verbose argv "/usr/bin/node" "/usr/bin/npm" "ci" "--pro"
14 verbose node v10.24.0
15 verbose npm  v6.14.11
16 error code ENOENT
17 error syscall open
18 error path /root/excalidraw-collaboration/package.json
19 error errno -2
20 error enoent ENOENT: no such file or directory, open '/root/excalidraw-collaboration/package.json'
21 error enoent This is related to npm not being able to find a file.
22 verbose exit [ -2, true ]

**Comment by jacknelson-sr** [comment]
显示缺少package.json文件

**Comment by alswl** [comment]
麻烦提供：操作系统版本，docker 版本，docker compose 版本，make 版本。以及具体的操作步骤。

从错误来看，访问了 `/root/excalidraw-collaboration/package.json`，而事实上，excalidraw-collaboration 不是一个 Node 项目，不会在这个目录进行 npm 构建。

**Comment by jacknelson-sr** [comment]
> 麻烦提供：操作系统版本，docker 版本，docker compose 版本，make 版本。以及具体的操作步骤。
> 
> 从错误来看，访问了 `/root/excalidraw-collaboration/package.json`，而事实上，excalidraw-collaboration 不是一个 Node 项目，不会在这个目录进行 npm 构建。

pve 7.3.4环境宿主机。 lxc容量。os是rockylinux 8.7。 docker v23。docker compose v2.15.1。make v4.2.1。操作步骤完全按你的部署说明。

**Comment by alswl** [comment]
表现比较奇怪，你可以尝试在你的环境下面直接构建一下 https://github.com/excalidraw/excalidraw 试试？

**Comment by jacknelson-sr** [comment]
> 表现比较奇怪，你可以尝试在你的环境下面直接构建一下 https://github.com/excalidraw/excalidraw 试试？

好的，感谢提示。顺便问一下，你部署的系统和版本是什么？我可以根据你的环境来试试，谢谢

**Comment by alswl** [comment]
@jacknelson-sr 

macOS (intel / m1) 都可以工作，有国外友人在 Linux 也有部署。

我本机信息：

```
➜  ~ docker version
Cannot connect to the Docker daemon at unix:///Users/xxx/.docker/run/docker.sock. Is the docker daemon running?
Client:
 Cloud integration: v1.0.29
 Version:           20.10.22
 API version:       1.41
 Go version:        go1.18.9
 Git commit:        3a2c30b
 Built:             Thu Dec 15 22:28:41 2022
 OS/Arch:           darwin/arm64
 Context:           desktop-linux
 Experimental:      true

➜  ~ make --version
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0

➜  ~ docker-compose --version
Docker Compose version v2.15.1
```

**Comment by jacknelson-sr** [comment]
> @jacknelson-sr
> 
> macOS (intel / m1) 都可以工作，有国外友人在 Linux 也有部署。
> 
> 我本机信息：
> 
> ```
> ➜  ~ docker version
> Cannot connect to the Docker daemon at unix:///Users/xxx/.docker/run/docker.sock. Is the docker daemon running?
> Client:
>  Cloud integration: v1.0.29
>  Version:           20.10.22
>  API version:       1.41
>  Go version:        go1.18.9
>  Git commit:        3a2c30b
>  Built:             Thu Dec 15 22:28:41 2022
>  OS/Arch:           darwin/arm64
>  Context:           desktop-linux
>  Experimental:      true
> 
> ➜  ~ make --version
> GNU Make 3.81
> Copyright (C) 2006  Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.
> There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
> PARTICULAR PURPOSE.
> 
> This program built for i386-apple-darwin11.3.0
> 
> ➜  ~ docker-compose --version
> Docker Compose version v2.15.1
> ```

我换了KVM环境的rockylinux，倒是完全没问题。LXC上确实不行。感谢你的指导，thx.

**Comment by alswl** [comment]
@jacknelson-sr 我怀疑是 LXC 的容器 mount 文件路径出现了一些预期外情况。

🤝

**Comment by jacknelson-sr** [comment]
我觉得也是make的路径问题。anyway再次感谢你的帮助。🤝
