### ISSUE TITLE
Docker compose up does not work out of the box

### ISSUE THREAD

**Issue by matbgn** [alswl/excalidraw-collaboration#9]
Running `docker compose up` end up with complain on master: 

```
Error response from daemon: pull access denied for excalidraw, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

Respectively, the patch complains on remote absence `make patch images`:
```
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/matbgn/Dev/excalidraw-collaboration/excalidraw/Dockerfile: no such file or directory
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/matbgn/Dev/excalidraw-collaboration/excalidraw-room/Dockerfile: no such file or directory
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/matbgn/Dev/excalidraw-collaboration/excalidraw-storage-backend/Dockerfile: no such file or directory
make: *** [Makefile:65: images] Error 1
```

**Comment by alswl** [comment]
> pull access denied for excalidraw

It means there is no `excalidraw` images in local docker engine, and the image should be build by `make images`.

> /home/matbgn/Dev/excalidraw-collaboration/excalidraw/Dockerfile: no such file or directory

Means there is no file in the position.
Did you run `git clone --recursive`, please NOTICE the `--recursive` will clone the sub modules of the project.

**Comment by matbgn** [comment]
Ok, a complete wipe of the folder and a careful follow-up of the instructions made it!

Kudos for your implementation, really!

I will post some thoughts on #7 as it seems promising here
